name: mlpy
channels:
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - matplotlib
  - seaborn
  - pandas
  - xlrd
  - wordcloud
  - folium
  - scikit-learn
  - pydotplus
  - basemap
  - nodejs
  - ipywidgets
  - jupyterlab
  - rise
